---
features:
  - |
    If a file `{{ node_custom_config }}/magnum/kubeconfig` exists, it is
    copied to `/var/lib/magnum/.kube/config` in all Magnum Service Containers.
    At this location, the `vexxhost/magnum-cluster-api` will loo for the Kubeconfig
    configuration file to control the Cluster API Control Plane. If the
    `vexxhost/magnum-cluster-api` is installed in the Magnum container images,
    control of a cluster API control plane can then take place via the Magnum API.

    Backport of https://review.opendev.org/c/openstack/kolla-ansible/+/896292
