---
dist: bionic
language: generic

before_install:
  - scripts/travis.sh

env:
  global:
    - REPOSITORY=osism/kolla-ansible
  matrix:
    - OPENSTACK_VERSION=master
    - OPENSTACK_VERSION=rocky
    - OPENSTACK_VERSION=stein
    - OPENSTACK_VERSION=train

before_script:
  - bash scripts/lint.sh

script:
  - bash scripts/build.sh
  - bash scripts/test.sh

deploy:
  - provider: script
    script: bash scripts/push.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bash scripts/push.sh
    skip_cleanup: true
    on:
      tags: true

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
