---
- secret:
    name: SECRET_CONTAINER_IMAGE_KOLLA_ANSIBLE
    data:
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - B6MwhYI5TvYv/R3q7DOkWpDHvAwaAUy0ySFSsc2cmkqv6ZYmwmOF1URxh4l8QUL2XSyV3
          BZ389udy7gE1CrJAtt2MJ4AzCP4k+9qMs0PT1lOcK4/LIZkAIgYo6C3KctTvx4IYEA6jP
          phBUaHHOW5f0XhTGbIFB2MbYmuze1sFBXfWkse7+po14kPQWhyYJbMNKBf4WscOnO0jbF
          LaZwkGMGIseFcz5A0EIjFL8CbhrH3joIILLNhA5GKqk4V0oZrumXJsP0ZbCGus6IpFoid
          jD9cIoBbKh5mNP/PtQn0qgLTV5Fl57QyFF7E7jGQ9qQgrZCvEy7ul32HVaUE62noB9f2J
          N9KkU7R9zKmcT9mamLvBpNdHk0hgC8VuBJBOFjQ66pMGwj+wOx7b/CWagn5k2TypaXeoS
          6QZAs6EwUdDN5S4OKpSKLxFBVW8hVgbkQqnf96+bx0iaUyRFcU0dzCSiNE7Wsx/iPc0GD
          S8EIQ6GkVLXcWQifuRnkxEDRoaYVjYlhin1WGKlJAxU3nomIB8O602W3gE2UQSqAig6d7
          7bOEsmCQDmnsb0ZtIltjTgrBEOwudfjwgaPWvbz3QdFtZbh/RaHV2jb4zI25FgpVNf7me
          RMs70VBkuAl/snP3N9gNw+ouYCp53uTqwTmDHyHoKfYXrxaxdiTmcBhNkPI3Kc=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - eDjoWvX8S82IhUFtzR9YqHbmd4YrToRMsWsD+VEKi/GB60eSTaO5K1Fptl1FDIK7GpEGo
          2djAl/4LmwBWmwgX3Xb6g1YKr7c54LTuemX9XJKGzsdKfb4ZKyP9Lo9/ihAsk69CHteFp
          PjIAqs//+ky85bKyj1LcJKf6JjYaF9BKfkIxlW3Ft9NNWGxfarJMAsbuldW9FKYrRzUf6
          Cn2B603wSXKL4CCuyU1QA4Uz/UW/uHABrUaq4nyOcU47hX8HphBYLSOjsqDlNPJ5emiJB
          o7v3Dpr0t2I25g+ylt55KrjAlu7n5/Feg/hbghAIP/M7N/j28JMqqh8a+DgVLJKRB2Ddr
          /iGmlxYC5kH0BwZsYdtRjILpsVmz48aZArZM/0zYo6Use7mIiUB/+Z/8dl0P2+T84Q//7
          PrhjMjs/Wa+nJIA6qJsgaSAetth0UC+TtBBtbmNapDOTH2TrNAzMjou8V0Vg2CStoPIuw
          jOqzsXP7BhAo/7xZgku16FI3oGJuhM3C5r6kqbRTJOri8Rx7Ed2StRPPRideBtoE4jMko
          DiaRHFVyBIuQVbS38oirkVu7iOFMMnhy9z/Dy5rQjn3W1dnmMmCq2WsIioZfL5S30Sntq
          +f3U0lv4jEFlPNqCkveCOYfxS8eiTAxLd63JBRM3yb+c0Zq0ci/SfVc9D6hfdM=

- job:
    name: container-image-kolla-ansible-build
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital

- job:
    name: container-image-kolla-ansible-build-yoga
    parent: container-image-kolla-ansible-build
    vars:
      version_openstack: yoga
      push_image: false

- job:
    name: container-image-kolla-ansible-build-zed
    parent: container-image-kolla-ansible-build
    vars:
      version_openstack: zed
      push_image: false

- job:
    name: container-image-kolla-ansible-push-yoga
    parent: image-build
    vars:
      version_openstack: yoga
      push_image: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_KOLLA_ANSIBLE
        pass-to-parent: true

- job:
    name: container-image-kolla-ansible-push-zed
    parent: image-build
    vars:
      version_openstack: zed
      push_image: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_KOLLA_ANSIBLE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - yamllint
        - container-image-kolla-ansible-build-yoga
        - container-image-kolla-ansible-build-zed
    gate:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - yamllint
    post:
      jobs:
        - container-image-kolla-ansible-push-yoga:
            branches: main
        - container-image-kolla-ansible-push-zed:
            branches: main
