---
- secret:
    name: SECRET_CONTAINER_IMAGE_KOLLA_ANSIBLE
    data:
      DTRACK_API_KEY: !encrypted/pkcs1-oaep
        - EEvz7G5rCESb+kMdyorXaAxcN33nt66zKcByqzXXjWpoxWKAvw1JX7k9ZSH8ArgA+OTKa
          2lRW3YIpJbPXkE5BScKWyQR03WmNONPVurTdPlKKjIBOyq4hZmuG2XdmM2jb3le74wboV
          xjdVQpE+M09ou857EL+A4Z8/6MHx6Eg2j1h2N+186zPzhVl+IOQWL/zeM6/WZy2RMT6ho
          +N4IoKWyTl9ZZ3nB7JzFftco+CqW8sLwbw5496aaftZWJSANIMy1TgoUUazV5Rpy7CV1t
          K1CjNewyMGiHNQTa99PyV6cKype53ZBbqbOGgsNtqkuRvWo5gI4ZTIO6rmFCcSotcQ9BB
          miCZBic4j2HwsdN7HNIwGIwKzrjsGQWVYwaI8ukLd4rpPLJ7/S7QP362+jDnHOczvdMM+
          TfIfsNx2t8h+M1E4w4l9NL/KgqfZmDtvrPwAubVCJ4GZKKBNOyfktiGlMNx1jDt+UYeHr
          PFvzzT0GjNoqrmQxZ0SsTrsvqlwx5zUDEzq/+7xzIOGzVWtCpZInLgZSfDjF94e+sKvY9
          cq8eEnfl8XmBkcnC8kiB7rl7jqtKNUccBqGI9Izg6C9mZkNvB+UicQy4syPHPp0gZWqmL
          dehmVuy8V3kxVrqu2WgvO/KoXOgCXNbnGK9CMyFGyJb4bPH/pwX7QdwrFUf3SU=
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - B6MwhYI5TvYv/R3q7DOkWpDHvAwaAUy0ySFSsc2cmkqv6ZYmwmOF1URxh4l8QUL2XSyV3
          BZ389udy7gE1CrJAtt2MJ4AzCP4k+9qMs0PT1lOcK4/LIZkAIgYo6C3KctTvx4IYEA6jP
          phBUaHHOW5f0XhTGbIFB2MbYmuze1sFBXfWkse7+po14kPQWhyYJbMNKBf4WscOnO0jbF
          LaZwkGMGIseFcz5A0EIjFL8CbhrH3joIILLNhA5GKqk4V0oZrumXJsP0ZbCGus6IpFoid
          jD9cIoBbKh5mNP/PtQn0qgLTV5Fl57QyFF7E7jGQ9qQgrZCvEy7ul32HVaUE62noB9f2J
          N9KkU7R9zKmcT9mamLvBpNdHk0hgC8VuBJBOFjQ66pMGwj+wOx7b/CWagn5k2TypaXeoS
          6QZAs6EwUdDN5S4OKpSKLxFBVW8hVgbkQqnf96+bx0iaUyRFcU0dzCSiNE7Wsx/iPc0GD
          S8EIQ6GkVLXcWQifuRnkxEDRoaYVjYlhin1WGKlJAxU3nomIB8O602W3gE2UQSqAig6d7
          7bOEsmCQDmnsb0ZtIltjTgrBEOwudfjwgaPWvbz3QdFtZbh/RaHV2jb4zI25FgpVNf7me
          RMs70VBkuAl/snP3N9gNw+ouYCp53uTqwTmDHyHoKfYXrxaxdiTmcBhNkPI3Kc=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - eDjoWvX8S82IhUFtzR9YqHbmd4YrToRMsWsD+VEKi/GB60eSTaO5K1Fptl1FDIK7GpEGo
          2djAl/4LmwBWmwgX3Xb6g1YKr7c54LTuemX9XJKGzsdKfb4ZKyP9Lo9/ihAsk69CHteFp
          PjIAqs//+ky85bKyj1LcJKf6JjYaF9BKfkIxlW3Ft9NNWGxfarJMAsbuldW9FKYrRzUf6
          Cn2B603wSXKL4CCuyU1QA4Uz/UW/uHABrUaq4nyOcU47hX8HphBYLSOjsqDlNPJ5emiJB
          o7v3Dpr0t2I25g+ylt55KrjAlu7n5/Feg/hbghAIP/M7N/j28JMqqh8a+DgVLJKRB2Ddr
          /iGmlxYC5kH0BwZsYdtRjILpsVmz48aZArZM/0zYo6Use7mIiUB/+Z/8dl0P2+T84Q//7
          PrhjMjs/Wa+nJIA6qJsgaSAetth0UC+TtBBtbmNapDOTH2TrNAzMjou8V0Vg2CStoPIuw
          jOqzsXP7BhAo/7xZgku16FI3oGJuhM3C5r6kqbRTJOri8Rx7Ed2StRPPRideBtoE4jMko
          DiaRHFVyBIuQVbS38oirkVu7iOFMMnhy9z/Dy5rQjn3W1dnmMmCq2WsIioZfL5S30Sntq
          +f3U0lv4jEFlPNqCkveCOYfxS8eiTAxLd63JBRM3yb+c0Zq0ci/SfVc9D6hfdM=

- semaphore:
    name: semaphore-container-image-kolla-ansible-push-bobcat
    max: 1

- semaphore:
    name: semaphore-container-image-kolla-ansible-push-caracal
    max: 1

- job:
    name: container-image-kolla-ansible-build
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital

- job:
    name: container-image-kolla-ansible-build-bobcat
    parent: container-image-kolla-ansible-build
    vars:
      version_openstack: "2023.2"

- job:
    name: container-image-kolla-ansible-build-caracal
    parent: container-image-kolla-ansible-build
    vars:
      version_openstack: "2024.1"

- job:
    name: container-image-kolla-ansible-push-bobcat
    parent: container-image-kolla-ansible-build
    semaphores:
      - name: semaphore-container-image-kolla-ansible-push-bobcat
    vars:
      version_openstack: "2023.2"
      push_image: true
      push_sbom: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_KOLLA_ANSIBLE
        pass-to-parent: true

- job:
    name: container-image-kolla-ansible-push-caracal
    parent: container-image-kolla-ansible-build
    semaphores:
      - name: semaphore-container-image-kolla-ansible-push-caracal
    vars:
      version_openstack: "2024.1"
      push_image: true
      push_sbom: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_KOLLA_ANSIBLE
        pass-to-parent: true

- job:
    name: container-image-kolla-ansible-release
    parent: container-image-kolla-ansible-build
    vars:
      push_image: true
      push_sbom: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_KOLLA_ANSIBLE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
        - container-image-kolla-ansible-build-bobcat
        - container-image-kolla-ansible-build-caracal
    gate:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
    periodic-midnight:
      jobs:
        - container-image-kolla-ansible-push-bobcat
        - container-image-kolla-ansible-push-caracal
    post:
      jobs:
        - container-image-kolla-ansible-push-bobcat:
            branches: main
        - container-image-kolla-ansible-push-caracal:
            branches: main
    tag:
      jobs:
        - container-image-kolla-ansible-release
