---
- secret:
    name: SECRET_CONTAINER_IMAGE_KOLLA_ANSIBLE
    data:
      DTRACK_API_KEY: !encrypted/pkcs1-oaep
        - eqLAE6q+7HG5+gNdHP9qJ6joM01bvjN/3r8oVY1HA6HTWh/AK1eD846DssKJzNMO/KIrw
          FuPKEmqnFglvQzEhMtZVgz2zPbKrbrT9fFBrJH+U/aTnVAauPybvqCkjYlqDHO+lw5iGG
          CJnHeEacIE9VHvqTdaKoaANjRUdErT1Yp+lBj3kfV0yACPPdU2Io1RVYm9A4deVAQTDcQ
          9L6tXj7BJpxO/8v22VBUYNDK9un40rYjy6bzePpWIXiA7EIuvl+UgTJDvAF9AVmGrKeW3
          Eg7V6bNYOlvqWMZ3KahvtnAjmV6BVgGv+R2FWQtSn3OoD9YKOmE98Tf/9Iz/R/36uS5FK
          SIi6t1qSGMG5oklTq7RmCUaVZr0DQ0g6zOJ0/ZU7c51Emf89XK3B/U4SiJxSfp998Ew8Y
          F+ey09W6+jjiRu4Whmwd1fcz8se8g2bnoBfG8Bbk8zan0aTgbT5cTxVqK2Tm6A8VnF1rh
          mWcShKwWGTSwzAQRHrLYBcfs5Dep5MuU7Q7RjrQZb0LNpiKr9UJpHnBloTp+ARmQNVL7v
          kBmjG1qTDNWdTLUqTNS8r8RQfAi5BDO5ohHgSWqDOnGCWSzxKuFGTEVhdRYxzKieapns4
          A9k14qdjdbDBvsdyS1C/y3em6htBhyEM604QJTERv69O3hnSZjP2VDc2g6uX/4=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - V+q5Nyt/8scU5fnhgOwHv9TbBQrB2PDuHg3vJ/xi+ctWaCMgPRa38gMnpBmskQdRgN1ZX
          8JAzv7vb6I1tb8m/6YPiv4hzhJ+9jBbC4Cxza5up9UHrj/nB/Fv7DEaLSDFJ2sxfW++WQ
          Ry4jhleORrLAafXUYWdYaWYYHef386CnIiNXLDkb4AzG44ZOvgUnFxLI+zNauVHq97Z5g
          CyiUBYtNEd/7INYy4j7DkwSgjkHT+gaD3kDFOBWrFCHp+3oWW+pi4wWJpg5hcYFXqd4qj
          WocWkI3jVKYBAAAW1wWuFwoh3KBiW/sAb30qxCufjzyb8OtSqFyURJgDG4NGOWcLc9Ua/
          MNMKHpFkwbW00v3yNodWPkcIJXOZ+Xsp8T33VvM8E5vLRJP5Bf7Bbu9MHOehpCmwsWkdV
          Y+orsEJBFVQTQpCtI79IGKE7vQyqMJqbKD5ZBs67E33LuySt9AjvG8p0OPuHBnoygB4fm
          KqJ18URIp/+YPy5QCM9vkhr5Y5sW9a5ByNYewoTnSKn7ElvtfHfrmLXgWoWbGQGHqCg2A
          QJiS6diB2YjbMmyWnauAgPiTIHOms0DXOeUlAojfP7Y0q0rdBx6SbfY/mTgBYXXbF3EWe
          ptXnVYsP1n33Gewo+3tGAnggbAHWqCUX+3LnXdVImxEtTWcWXs+vtVpQ8b4ktw=
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - j6iELK8BgKU+cFFiGN0whwQhxxesZZ80o4BfQLecO3Kd2pX/2tSbGlYg4/DPZTLe5TQwy
          LUMCs37VDu0eSgEcO4UYm8ixFJLx/78bjxUQoEuOLmW77IjkvzqtlmpWwRat7EJee1VaJ
          98v2b4xDXsygbj4ZsWCqTVtaWNjhyn9Ofx2PmhjgDI0SdLDpJJDaiLBbTgdAYX0PCKKW9
          Oj9hxHRBOQXzTTD3tX/moHlG0TERlTZz4rrwl7AIbBpP7XyxQCGAhiZsfnUXlDRWbq+XH
          XZg5iobwiTfXVom0Tj+KEM6vIRAaFdTKlfB2oZ8GO4IIv5N6RaRmjy7DdmdtqYOrZSR0/
          3PTgDiK5Yov5kif4b5y69xUrB/n4VwnY7zN+ctLbXvYFUhackpnGrJBQ2HOQTaeNAP7Or
          PAlgD7APBOZEwXmbHQjxEVuXfjrNmuZtC0/pPgPclar8rfAHG6xIkxp/fncYOmgDxg7sM
          ljx/J7ZMb01Ium9EvD4VFYnsUG0F2jfUxdsGYPiqfE00wpvuNhz6kvYs9h+x8PQDc+/OM
          tsGvd2YTP5XcCfYIXpteLxltm/T9jK1zX4OND9dFf0Fz1x6IPA6h+OXJICCtbLWtPJFsr
          o0BdRbbviuSssQEBf4zq+p4NBPZU50Vihhkvfp7tf6EaZRSSBTjTu5dXjf/BTs=

- semaphore:
    name: semaphore-container-image-kolla-ansible-push-2024.1
    max: 1

- semaphore:
    name: semaphore-container-image-kolla-ansible-push-2024.2
    max: 1

- job:
    name: container-image-kolla-ansible-build
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital

- job:
    name: container-image-kolla-ansible-build-2024.1
    parent: container-image-kolla-ansible-build
    vars:
      version_openstack: "2024.1"

- job:
    name: container-image-kolla-ansible-build-2024.2
    parent: container-image-kolla-ansible-build
    vars:
      version_openstack: "2024.2"

- job:
    name: container-image-kolla-ansible-push-2024.1
    parent: container-image-kolla-ansible-build
    semaphores:
      - name: semaphore-container-image-kolla-ansible-push-2024.1
    vars:
      version_openstack: "2024.1"
      push_image: true
      push_sbom: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_KOLLA_ANSIBLE
        pass-to-parent: true

- job:
    name: container-image-kolla-ansible-push-2024.2
    parent: container-image-kolla-ansible-build
    semaphores:
      - name: semaphore-container-image-kolla-ansible-push-2024.2
    vars:
      version_openstack: "2024.2"
      push_image: true
      push_sbom: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_KOLLA_ANSIBLE
        pass-to-parent: true

- job:
    name: container-image-kolla-ansible-release
    parent: container-image-kolla-ansible-build
    vars:
      push_image: true
      push_sbom: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_KOLLA_ANSIBLE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
        - container-image-kolla-ansible-build-2024.1
        - container-image-kolla-ansible-build-2024.2
    gate:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
    periodic-midnight:
      jobs:
        - container-image-kolla-ansible-push-2024.1
        - container-image-kolla-ansible-push-2024.2
    post:
      jobs:
        - container-image-kolla-ansible-push-2024.1:
            branches: main
        - container-image-kolla-ansible-push-2024.2:
            branches: main
    tag:
      jobs:
        - container-image-kolla-ansible-release
