# SPDX-License-Identifier: Apache-2.0

import os
import sys

import yaml

# get environment parameters

VERSION = os.environ.get("VERSION", "latest")

# load versions files from release repository

with open("/release/latest/base.yml", "rb") as fp:
    versions = yaml.load(fp, Loader=yaml.FullLoader)

with open("/release/etc/collections.yml", "rb") as fp:
    collection_repositories = yaml.load(fp, Loader=yaml.FullLoader)

with open("/src/collections.yml", "rb") as fp:
    collection_names = yaml.load(fp, Loader=yaml.FullLoader)

# NOTE: Every collection is installed at the version pinned in the release
#       repository, except that a latest build takes the OSISM collections
#       from their main branch, as container-image-osism-ansible does.

missing = [
    name for name in collection_names if name not in versions["ansible_collections"]
]
if missing:
    sys.exit(
        "not pinned in ansible_collections of the release repository: "
        + ", ".join(missing)
    )

collections = []
for name in collection_names:
    if VERSION == "latest" and name in collection_repositories:
        collections.append(
            {
                "name": f"https://github.com/{collection_repositories[name]}.git",
                "type": "git",
                "version": "main",
            }
        )
    else:
        collections.append(
            {
                "name": name,
                "source": "https://galaxy.ansible.com",
                "version": versions["ansible_collections"][name],
            }
        )

# render requirements.yml

with open("/ansible/galaxy/requirements.yml", "w+") as fp:
    fp.write(
        "---\n# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN\n\n"
    )
    yaml.safe_dump({"roles": [], "collections": collections}, fp, sort_keys=False)
