---
- name: Group hosts based on configuration
  hosts:
    - mariadb
  gather_facts: false
  tasks:
    - name: Group hosts based on Kolla action
      group_by:
        key: kolla_action_{{ kolla_action }}
      changed_when: false
    - name: Group hosts based on enabled services
      group_by:
        key: '{{ item }}'
      changed_when: false
      with_items: enable_mariadb_{{ enable_mariadb | bool }}
  tags: always

# For MariaDB we need to be careful about restarting services, to avoid losing quorum.
- name: Apply role mariadb
  gather_facts: false
  hosts:
    - mariadb
    - '&enable_mariadb_True'
  tags:
    - mariadb
  tasks:
    - import_role:
        name: mariadb

- name: Restart mariadb services
  gather_facts: false
  hosts:
    - mariadb_restart
    - '&enable_mariadb_True'
  # Restart in batches
  serial: "33%"
  tags:
    - mariadb
  tasks:
    - import_role:
        name: mariadb
        tasks_from: restart_services.yml

- name: Start mariadb services
  gather_facts: false
  hosts:
    - mariadb_start
    - '&enable_mariadb_True'
  # Start in batches
  serial: "33%"
  tags:
    - mariadb
  tasks:
    - import_role:
        name: mariadb
        tasks_from: restart_services.yml

- name: Restart bootstrap mariadb service
  gather_facts: false
  hosts:
    - mariadb_bootstrap_restart
    - '&enable_mariadb_True'
  tags:
    - mariadb
  tasks:
    - import_role:
        name: mariadb
        tasks_from: restart_services.yml

- name: Apply mariadb post-configuration
  gather_facts: false
  hosts:
    - mariadb
    - '&enable_mariadb_True'
  tags:
    - mariadb
  tasks:
    - name: Include mariadb post-deploy.yml
      include_role:
        name: mariadb
        tasks_from: post-deploy.yml
      when: kolla_action in ['deploy', 'reconfigure', 'upgrade']

    - name: Include mariadb post-upgrade.yml
      include_role:
        name: mariadb
        tasks_from: post-upgrade.yml
      when: kolla_action == 'upgrade'
