---
- name: Group hosts based on configuration
  hosts: all
  gather_facts: false
  tasks:
    - name: Group hosts based on OpenStack release
      group_by:
          key: openstack_release_{{ openstack_release }}
    - name: Group hosts based on Kolla action
      group_by:
          key: kolla_action_{{ kolla_action }}
    - name: Group hosts based on enabled services
      group_by:
          key: '{{ item }}'
      with_items:
        - enable_aodh_{{ enable_aodh | bool }}
        - enable_barbican_{{ enable_barbican | bool }}
        - enable_blazar_{{ enable_blazar | bool }}
        - enable_ceilometer_{{ enable_ceilometer | bool }}
        - enable_ceph_{{ enable_ceph | bool }}
        - enable_chrony_{{ enable_chrony | bool }}
        - enable_cinder_{{ enable_cinder | bool }}
        - enable_cloudkitty_{{ enable_cloudkitty | bool }}
        - enable_collectd_{{ enable_collectd | bool }}
        - enable_congress_{{ enable_congress | bool }}
        - enable_cyborg_{{ enable_cyborg | bool }}
        - enable_designate_{{ enable_designate | bool }}
        - enable_elasticsearch_{{ enable_elasticsearch | bool }}
        - enable_etcd_{{ enable_etcd | bool }}
        - enable_freezer_{{ enable_freezer | bool }}
        - enable_glance_{{ enable_glance | bool }}
        - enable_gnocchi_{{ enable_gnocchi | bool }}
        - enable_grafana_{{ enable_grafana | bool }}
        - enable_haproxy_{{ enable_haproxy | bool }}
        - enable_heat_{{ enable_heat | bool }}
        - enable_horizon_{{ enable_horizon | bool }}
        - enable_hyperv_{{ enable_hyperv | bool }}
        - enable_influxdb_{{ enable_influxdb | bool }}
        - enable_ironic_{{ enable_ironic | bool }}
        - enable_iscsid_{{ enable_iscsid | bool }}
        - enable_kafka_{{ enable_kafka | bool }}
        - enable_karbor_{{ enable_karbor | bool }}
        - enable_keystone_{{ enable_keystone | bool }}
        - enable_kibana_{{ enable_kibana | bool }}
        - enable_kuryr_{{ enable_kuryr | bool }}
        - enable_magnum_{{ enable_magnum | bool }}
        - enable_manila_{{ enable_manila | bool }}
        - enable_mariadb_{{ enable_mariadb | bool }}
        - enable_masakari_{{ enable_masakari | bool }}
        - enable_memcached_{{ enable_memcached | bool }}
        - enable_mistral_{{ enable_mistral | bool }}
        - enable_monasca_{{ enable_monasca | bool }}
        - enable_mongodb_{{ enable_mongodb | bool }}
        - enable_multipathd_{{ enable_multipathd | bool }}
        - enable_murano_{{ enable_murano | bool }}
        - enable_neutron_{{ enable_neutron | bool }}
        - enable_nova_{{ enable_nova | bool }}
        - enable_octavia_{{ enable_octavia | bool }}
        - enable_opendaylight_{{ enable_opendaylight | bool }}
        - enable_openvswitch_{{ enable_openvswitch | bool }}
        - enable_ovs_dpdk_{{ enable_ovs_dpdk | bool }}
        - enable_outward_rabbitmq_{{ enable_outward_rabbitmq | bool }}
        - enable_panko_{{ enable_panko | bool }}
        - enable_placement_{{ enable_placement | bool }}
        - enable_prometheus_{{ enable_prometheus | bool }}
        - enable_qdrouterd_{{ enable_qdrouterd | bool }}
        - enable_qinling_{{ enable_qinling | bool }}
        - enable_rabbitmq_{{ enable_rabbitmq | bool }}
        - enable_rally_{{ enable_rally | bool }}
        - enable_redis_{{ enable_redis | bool }}
        - enable_sahara_{{ enable_sahara | bool }}
        - enable_searchlight_{{ enable_searchlight | bool }}
        - enable_senlin_{{ enable_senlin | bool }}
        - enable_skydive_{{ enable_skydive | bool }}
        - enable_solum_{{ enable_solum | bool }}
        - enable_swift_{{ enable_swift | bool }}
        - enable_tacker_{{ enable_tacker | bool }}
        - enable_telegraf_{{ enable_telegraf | bool }}
        - enable_tempest_{{ enable_tempest | bool }}
        - enable_trove_{{ enable_trove | bool }}
        - enable_vitrage_{{ enable_vitrage | bool }}
        - enable_vmtp_{{ enable_vmtp | bool }}
        - enable_watcher_{{ enable_watcher | bool }}
        - enable_zookeeper_{{ enable_zookeeper | bool }}
        - enable_zun_{{ enable_zun | bool }}
  tags: always

- name: Run haproxy playbook
  import_playbook: kolla-haproxy.yml

- name: Apply infrastructure roles
  gather_facts: no
  hosts: control
  serial: '{{ kolla_serial|default("0") }}'
  roles:
    - role: common
    - role: elasticsearch
    - role: openvswitch
    - role: memcached
    - role: redis
    - role: etcd
    - role: mariadb
    - role: kibana

- name: Run rabbitmq playbook
  import_playbook: kolla-rabbitmq.yml

- name: Apply base openstack roles
  gather_facts: no
  hosts: control
  serial: '{{ kolla_serial|default("0") }}'
  roles:
    - role: keystone
    - role: horizon
    - role: placement
      when: openstack_release != 'rocky'
    - role: glance
    - role: cinder
    - role: neutron

- name: Run nova playbook
  import_playbook: kolla-nova.yml
