---
- name: Group hosts based on configuration
  hosts:
    - iscsid
    - tgtd
  gather_facts: false
  tasks:
    - name: Group hosts based on Kolla action
      ansible.builtin.group_by:
        key: kolla_action_{{ kolla_action }}
      changed_when: false
    - name: Group hosts based on enabled services
      ansible.builtin.group_by:
        key: '{{ item }}'
      changed_when: false
      with_items: enable_iscsid_{{ enable_iscsid | bool }}
  tags: always

- name: Apply role iscsi
  gather_facts: false
  hosts:
    - iscsid
    - tgtd
    - '&enable_iscsid_True'
  serial: '{{ kolla_serial | default("0") }}'
  roles:
    - role: iscsi
      tags: iscsi
