---
- name: Include ironic download images play
  ansible.builtin.import_playbook: kolla-ironic-download-ipa-images.yml

- name: Group hosts based on configuration
  hosts:
    - ironic-api
    - ironic-conductor
    - ironic-inspector
    - ironic-tftp
    - ironic-http
  gather_facts: false
  tasks:
    - name: Group hosts based on Kolla action
      ansible.builtin.group_by:
        key: kolla_action_{{ kolla_action }}
      changed_when: false
    - name: Group hosts based on enabled services
      ansible.builtin.group_by:
        key: '{{ item }}'
      changed_when: false
      with_items:
        - enable_ironic_{{ enable_ironic | bool }}
  tags: always

- name: Apply role ironic
  gather_facts: false
  hosts:
    - ironic-api
    - ironic-conductor
    - ironic-inspector
    - ironic-tftp
    - ironic-http
    - '&enable_ironic_True'
  serial: '{{ kolla_serial | default("0") }}'
  roles:
    - role: ironic
      tags: ironic
