---
- name: Gather facts for all hosts
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.setup:

- name: Gather facts for all hosts (if using --limit)
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.setup:
      delegate_facts: true
      delegate_to: "{{ item }}"
      with_items: "{{ groups['all'] }}"
      when:
        - (play_hosts | length) != (groups['all'] | length)
