---
- name: Group hosts based on configuration
  hosts:
    - compute
  gather_facts: false
  tasks:
    - name: Group hosts based on Kolla action
      ansible.builtin.group_by:
        key: kolla_action_{{ kolla_action }}
    - name: Group hosts based on enabled services
      ansible.builtin.group_by:
        key: '{{ item }}'
      with_items:
        - enable_nova_{{ enable_nova | bool }}
  tags: always

- name: Apply role nova-cell
  gather_facts: false
  hosts:
    - compute
    - '&enable_nova_True'
  serial: '{{ kolla_serial | default("0") }}'
  roles:
    - role: nova-cell
      when: enable_nova | bool
