---
- name: Write bifrost keypair
  hosts: manager
  gather_facts: false
  become: false

  vars:
    bifrost_private_key_file: "{{ ansible_env.HOME }}/.ssh/id_rsa.bifrost"
    bifrost_public_key_file: "{{ ansible_env.HOME }}/.ssh/id_rsa.bifrost.pub"

  tasks:
    - name: "Write {{ bifrost_private_key_file }}"
      ansible.builtin.template:
        src: bifrost-private-key-config.j2
        dest: "{{ bifrost_private_key_file }}"
        mode: 0600
        owner: "{{ operator_user }}"
        group: "{{ operator_group }}"

    - name: "Write {{ bifrost_public_key_file }}"
      ansible.builtin.template:
        src: bifrost-public-key-config.j2
        dest: "{{ bifrost_public_key_file }}"
        mode: 0600
        owner: "{{ operator_user }}"
        group: "{{ operator_group }}"
