---
- name: Group hosts based on configuration
  hosts:
    - nova
  gather_facts: false
  tasks:
    - name: Group hosts based on Kolla action
      ansible.builtin.group_by:
        key: kolla_action_{{ kolla_action }}
      changed_when: false
    - name: Group hosts based on enabled services
      ansible.builtin.group_by:
        key: '{{ item }}'
      changed_when: false
      with_items:
        - enable_nova_{{ enable_nova | bool }}
  tags: always

- name: Wait for the Nova service
  gather_facts: false
  hosts:
    - nova
    - '&enable_nova_True'
  serial: '{{ kolla_serial | default("0") }}'

  tasks:
    - name: Waiting for Nova public port to be UP
      ansible.builtin.wait_for:
        host: "{{ api_interface_address }}"
        port: "{{ nova_api_public_port }}"
        connect_timeout: 1
      register: check_nova_public_port
      until: check_nova_public_port is success
      retries: 60
      delay: 10
