---
- name: Create keystone service, user and endpoint for Ceph RGW
  hosts: control
  gather_facts: false

  vars:
    project_name: rgw-endpoint

    swift_keystone_user: swift

    swift_ks_services:
      - name: "swift"
        type: "object-store"
        description: "Openstack Object Storage"
        endpoints:
          - {'interface': 'admin', 'url': '{{ swift_admin_endpoint }}'}
          - {'interface': 'internal', 'url': '{{ swift_internal_endpoint }}'}
          - {'interface': 'public', 'url': '{{ swift_public_endpoint }}'}

    swift_ks_users:
      - project: "service"
        user: "{{ swift_keystone_user }}"
        password: "{{ swift_keystone_password }}"
        role: "admin"

  tasks:
    - import_role:
        name: service-ks-register
      vars:
        service_ks_register_auth: "{{ openstack_auth }}"
        service_ks_register_services: "{{ swift_ks_services }}"
        service_ks_register_users: "{{ swift_ks_users }}"
      run_once: true

    - name: Creating the ResellerAdmin role
      become: true
      kolla_toolbox:
        module_name: "os_keystone_role"
        module_args:
          name: "ResellerAdmin"
          region_name: "{{ openstack_region_name }}"
          auth: "{{ openstack_auth }}"
          endpoint_type: "{{ openstack_interface }}"
          cacert: "{{ openstack_cacert }}"
      run_once: true
