---
name: Build container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - files/**
      - patches/**
      - scripts/**
  pull_request:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - files/**
      - patches/**
      - scripts/**

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openstack_version:
          - victoria
          - wallaby
          - master
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          OPENSTACK_VERSION: ${{ matrix.openstack_version }}
          REPOSITORY: osism/kolla-ansible
      - run: |
          scripts/push.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          OPENSTACK_VERSION: ${{ matrix.openstack_version }}
          REPOSITORY: osism/kolla-ansible
        if: |
          github.repository == 'osism/container-image-kolla-ansible' &&
          github.ref == 'refs/heads/main'
