---
name: Build container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - main
  pull_request:

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openstack_version:
          - yoga
          - zed
          - master
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build container image
        run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          OPENSTACK_VERSION: ${{ matrix.openstack_version }}
          REPOSITORY: osism/kolla-ansible

      - name: Get short revision ID
        id: revision
        shell: bash
        run: echo "::set-output name=short::$(git rev-parse --short HEAD)"

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          artifact-name: kolla-ansible-${{ matrix.openstack_version }}.spdx
          image: "kolla-ansible:${{ steps.revision.outputs.short }}"

      - name: Push container image
        run: |
          scripts/push.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          OPENSTACK_VERSION: ${{ matrix.openstack_version }}
          REPOSITORY: osism/kolla-ansible
        if: |
          github.repository == 'osism/container-image-kolla-ansible' &&
          github.ref == 'refs/heads/main'
