---
name: Release docker image

"on":
  push:
    tags:
      - '*'

jobs:
  release-docker-image:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup docker
      #   uses: docker/setup-buildx-action@v1

      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build docker image
        run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          GIT_SHA: ${{ github.sha }}
          REPOSITORY: osism/kolla-ansible
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Push docker image
        run: |
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REPOSITORY: osism/kolla-ansible
          VERSION: ${{ steps.get_version.outputs.VERSION }}
